[versions]
# Kotlin
kotlin = "2.3.0"
serialization = "1.9.0"
coroutines = "1.10.2"
datetime = "0.7.1"

# Android
agp = "9.0.0"
compileSdk = "36"
minSdk = "30"
activity = "1.12.2"
material = "1.13.0"

# Compose
compose = "1.10.0"
material-icons = "1.7.3"
material3 = "1.10.0-alpha05"
navigation3 = "1.0.0-alpha06"
adaptive = "1.3.0-alpha02"
lifecycle = "2.10.0-alpha06"

# Compose Wear
compose-wear = "1.5.6"

# GMS
play-services-wearable = "19.0.0"

# Data
sqldelight = "2.2.1"

[libraries]
# Compose
compose-foundation = { module = "org.jetbrains.compose.foundation:foundation", version.ref = "compose" }
compose-ui = { module = "org.jetbrains.compose.ui:ui", version.ref = "compose" }
compose-runtime = { module = "org.jetbrains.compose.runtime:runtime", version.ref = "compose" }
compose-material3 = { module = "org.jetbrains.compose.material3:material3", version.ref = "material3" }
compose-material-icons-core = { module = "org.jetbrains.compose.material:material-icons-core", version.ref = "material-icons" }
compose-material-icons-extended = { module = "org.jetbrains.compose.material:material-icons-extended", version.ref = "material-icons" }
compose-navigation3-ui = { module = "org.jetbrains.androidx.navigation3:navigation3-ui", version.ref = "navigation3" }
compose-components-resources = { module = "org.jetbrains.compose.components:components-resources", version.ref = "compose" }
compose-material3-adaptive-navigation3 = { module = "org.jetbrains.compose.material3.adaptive:adaptive-navigation3", version.ref = "adaptive" }
lifecycle-navigation3 = { module = "org.jetbrains.androidx.lifecycle:lifecycle-viewmodel-navigation3", version.ref = "lifecycle" }
lifecycle-runtime = { module = "org.jetbrains.androidx.lifecycle:lifecycle-runtime-compose", version.ref = "lifecycle" }

kotlinx-json = { module = "org.jetbrains.kotlinx:kotlinx-serialization-json", version.ref = "serialization" }
kotlinx-coroutines-swing = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-swing", version.ref = "coroutines" }
kotlinx-datetime = { module = "org.jetbrains.kotlinx:kotlinx-datetime", version.ref = "datetime" }
kotlinx-coroutines-play-services = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-play-services", version.ref = "coroutines" }

sqldelight-android = { module = "app.cash.sqldelight:android-driver", version.ref = "sqldelight" }
sqldelight-jvm = { module = "app.cash.sqldelight:sqlite-driver", version.ref = "sqldelight" }
sqldelight-coroutines = { module = "app.cash.sqldelight:coroutines-extensions", version.ref = "sqldelight" }

# Android
androidx-activity-compose = { module = "androidx.activity:activity-compose", version.ref = "activity" }
material = { module = "com.google.android.material:material", version.ref = "material" }

# WearOS
wear-compose-foundation = { module = "androidx.wear.compose:compose-foundation", version.ref = "compose-wear" }
wear-compose-material3 = { module = "androidx.wear.compose:compose-material3", version.ref = "compose-wear" }
wear-compose-navigation = { module = "androidx.wear.compose:compose-navigation", version.ref = "compose-wear" }
play-services-wearable = { module = "com.google.android.gms:play-services-wearable", version.ref = "play-services-wearable" }


[plugins]
# Kotlin
kotlin-multiplatform = { id = "org.jetbrains.kotlin.multiplatform", version.ref = "kotlin" }
kotlin-serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }
kotlin-compose = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
kotlin-parcelize = { id = "org.jetbrains.kotlin.plugin.parcelize", version.ref = "kotlin" }

# Android
android-application = { id = "com.android.application", version.ref = "agp" }
android-multiplatform-library = { id = "com.android.kotlin.multiplatform.library", version.ref = "agp" }

# Compose
jetbrains-compose = { id = "org.jetbrains.compose", version.ref = "compose" }

# Data
sqldelight = { id = "app.cash.sqldelight", version.ref = "sqldelight" }