name: Build tag
on:
  push:
    tags:
      - '*.*.*'

jobs:
  build-jar:
    name: Build JAR
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ ubuntu-latest, windows-latest, macos-latest ]
    env:
      GRADLE_WRAPPER_SCRIPT: ${{ matrix.os == 'windows-latest' && '.\gradlew.bat' || './gradlew' }}
    steps:
      - name: Checkout sources
        uses: actions/checkout@v6

      - name: Setup JDK 25
        uses: actions/setup-java@v5
        with:
          distribution: temurin
          java-version: 25

      - name: Set gradle permission
        run: chmod +x gradlew
        if: env.RUNNER_OS != 'Windows'

      - name: Build JAR
        run: |
          ${{ env.GRADLE_WRAPPER_SCRIPT }} --no-daemon packageReleaseUberJarForCurrentOS \
            -Papp.version=${{ github.ref_name }}

      - name: Upload JAR
        uses: actions/upload-artifact@v6
        with:
          name: pixelcount-${{ matrix.os }}
          path: kmp/build/compose/jars/PixelCount-*-release.jar

  build-android-bundle:
    name: Build Android Bundle
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v6

      - name: Setup JDK 25
        uses: actions/setup-java@v5
        with:
          distribution: temurin
          java-version: 25

      - name: Setup Android SDK
        uses: android-actions/setup-android@v3

      - name: Set gradle permission
        run: chmod +x gradlew

      - name: Write keystore
        run: echo "${{ secrets.KEYSTORE }}" | base64 --decode > keystore.jks

      - name: Get version code
        run: echo "VERSION_CODE=$(echo ${{ github.ref_name}} | tr -d '.')$(git rev-list --count HEAD)" > $GITHUB_ENV

      - name: Build Android Bundle
        run: |
          ./gradlew --no-daemon :androidApp:bundleRelease -Pandroid.sign=true -Pandroid.storeFile=${{ github.workspace }}/keystore.jks \
            -Pandroid.storePassword="${{ secrets.KEYSTORE_PASSWORD }}" -Pandroid.alias=${{ secrets.KEY_ALIAS }} \
            -Pandroid.keyPassword="${{ secrets.KEY_PASSWORD }}" -Papp.version=${{ github.ref_name }} \
            -Papp.versionCode=1${{ env.VERSION_CODE }}

      - name: Build WearOs Bundle
        run: |
          ./gradlew --no-daemon :wearOs:bundleRelease -Pandroid.sign=true -Pandroid.storeFile=${{ github.workspace }}/keystore.jks \
            -Pandroid.storePassword="${{ secrets.KEYSTORE_PASSWORD }}" -Pandroid.alias=${{ secrets.KEY_ALIAS }} \
            -Pandroid.keyPassword="${{ secrets.KEY_PASSWORD }}" -Papp.version=${{ github.ref_name }} \
            -Papp.versionCode=2${{ env.VERSION_CODE }}

      - name: Upload Android Bundle
        uses: actions/upload-artifact@v6
        with:
          name: pixelcount-android
          path: androidApp/build/outputs/bundle/release/androidApp-release.aab

      - name: Upload Wear OS Bundle
        uses: actions/upload-artifact@v6
        with:
          name: pixelcount-wearos
          path: wearosApp/build/outputs/bundle/release/wearosApp-release.aab