on:
  push:
    branches:
      - main

jobs:
  build-jar:
    name: Build JAR
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    env:
      GRADLE_WRAPPER_SCRIPT: ${{ matrix.os == 'windows-latest' && '.\gradlew.bat' || './gradlew' }}
    steps:
      - name: Checkout sources
        uses: actions/checkout@v6

      - name: Setup JDK 25
        uses: actions/setup-java@v5
        with:
          distribution: temurin
          java-version: 25

      - name: Set gradle permission
        run: chmod +x gradlew
        if: env.RUNNER_OS != 'Windows'

      - name: Build JAR
        run: ${{ env.GRADLE_WRAPPER_SCRIPT }} --no-daemon packageReleaseUberJarForCurrentOS

      - name: Upload JAR
        uses: actions/upload-artifact@v6
        with:
          name: pixelcount-${{ matrix.os }}
          path: kmp/build/compose/jars/pixelcount-*-release.jar