name: Build
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
    types:
      - synchronize

jobs:
  build-jar:
    name: Build JAR
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest, macos-15-intel]
    env:
      GRADLE_WRAPPER_SCRIPT: ${{ matrix.os == 'windows-latest' && '.\gradlew.bat' || './gradlew' }}
    steps:
      - name: Checkout sources
        uses: actions/checkout@v6

      - name: Setup JDK 25
        uses: actions/setup-java@v5
        with:
          distribution: temurin
          java-version: 25

      - name: Set gradle permission
        run: chmod +x gradlew
        if: env.RUNNER_OS != 'Windows'

      - name: Build JAR
        run: ${{ env.GRADLE_WRAPPER_SCRIPT }} --no-daemon packageUberJarForCurrentOS

  build-android-bundle:
    name: Build Android Bundle
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v6

      - name: Setup JDK 25
        uses: actions/setup-java@v5
        with:
          distribution: temurin
          java-version: 25

      - name: Setup Android SDK
        uses: android-actions/setup-android@v3

      - name: Set gradle permission
        run: chmod +x gradlew

      - name: Build Android Bundle
        run: |
          ./gradlew --no-daemon bundleDebug
