name: Build tag
on:
  push:
    tags:
      - '*.*.*'

jobs:
  build-jar:
    name: Build JAR
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ ubuntu-latest, windows-latest, macos-latest, macos-15-intel ]
    env:
      GRADLE_WRAPPER_SCRIPT: ${{ matrix.os == 'windows-latest' && '.\gradlew.bat' || './gradlew' }}
    steps:
      - name: Checkout sources
        uses: actions/checkout@v6

      - name: Setup JDK 25
        uses: actions/setup-java@v5
        with:
          distribution: temurin
          java-version: 25

      - name: Set gradle permission
        run: chmod +x gradlew
        if: env.RUNNER_OS != 'Windows'

      - name: Build JAR
        run: |
          ${{ env.GRADLE_WRAPPER_SCRIPT }} --no-daemon packageReleaseUberJarForCurrentOS '-Papp.version=${{ github.ref_name }}'

      - name: Upload JAR
        uses: actions/upload-artifact@v6
        with:
          name: pixelcount-${{ matrix.os }}
          path: kmp/build/compose/jars/PixelCount-*-release.jar

  build-android-bundle:
    name: Build Android Bundle
    runs-on: ubuntu-latest
    outputs:
      artifacts: ${{ steps.publish-android.outputs.artifact-id }},${{ steps.publish-wearos.outputs.artifact-id }}
    steps:
      - name: Checkout sources
        uses: actions/checkout@v6

      - name: Setup JDK 25
        uses: actions/setup-java@v5
        with:
          distribution: temurin
          java-version: 25

      - name: Setup Android SDK
        uses: android-actions/setup-android@v3

      - name: Set gradle permission
        run: chmod +x gradlew

      - name: Write keystore
        run: echo "${{ secrets.KEYSTORE }}" | base64 --decode > keystore.jks

      - name: Get version code
        run: echo "VERSION_CODE=$(echo ${{ github.ref_name}} | tr -d '.')$(git rev-list --count HEAD)" > $GITHUB_ENV

      - name: Build Android Bundle
        run: |
          ./gradlew --no-daemon :androidApp:bundleRelease -Pandroid.sign=true -Pandroid.storeFile=${{ github.workspace }}/keystore.jks \
            -Pandroid.storePassword="${{ secrets.KEYSTORE_PASSWORD }}" -Pandroid.alias=${{ secrets.KEY_ALIAS }} \
            -Pandroid.keyPassword="${{ secrets.KEY_PASSWORD }}" -Papp.version=${{ github.ref_name }} \
            -Papp.versionCode=${{ env.VERSION_CODE }}1

      - name: Build WearOs Bundle
        run: |
          ./gradlew --no-daemon :wearosApp:bundleRelease -Pandroid.sign=true -Pandroid.storeFile=${{ github.workspace }}/keystore.jks \
            -Pandroid.storePassword="${{ secrets.KEYSTORE_PASSWORD }}" -Pandroid.alias=${{ secrets.KEY_ALIAS }} \
            -Pandroid.keyPassword="${{ secrets.KEY_PASSWORD }}" -Papp.version=${{ github.ref_name }} \
            -Papp.versionCode=${{ env.VERSION_CODE }}2

      - name: Upload Android Bundle
        uses: actions/upload-artifact@v6
        id: publish-android
        with:
          name: pixelcount-android
          path: androidApp/build/outputs/bundle/release/androidApp-release.aab

      - name: Upload Wear OS Bundle
        uses: actions/upload-artifact@v6
        id: publish-wearos
        with:
          name: pixelcount-wearos
          path: wearosApp/build/outputs/bundle/release/wearosApp-release.aab

  publish-google-play:
    name: Publish AAB to Google Play
    needs: build-android-bundle
    runs-on: ubuntu-latest
    steps:
      - name: Download Android artifact
        uses: actions/download-artifact@v7
        with:
          artifact-ids: ${{ needs.build-android-bundle.outputs.artifacts }}

      - name: Publish Android to Play Store
        uses: r0adkll/upload-google-play@v1
        with:
          releaseFiles: 'pixelcount-android/androidApp-release.aab'
          serviceAccountJsonPlainText: ${{ secrets.PLAY_STORE_SERVICE_ACCOUNT }}
          packageName: dev.vicart.pixelcount
          track: internal
          status: draft

      - name: Publish WearOS to Play Store
        uses: r0adkll/upload-google-play@v1
        with:
          releaseFiles: 'pixelcount-wearos/wearosApp-release.aab'
          serviceAccountJsonPlainText: ${{ secrets.PLAY_STORE_SERVICE_ACCOUNT }}
          packageName: dev.vicart.pixelcount
          track: wear:internal
          status: draft

  create-release:
    name: Create release tag
    needs: [ build-jar, build-android-bundle ]
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v7

      - name: Create release tag
        uses: softprops/action-gh-release@v2
        with:
          name: v${{ github.ref_name }}
          files: |
            pixelcount-android/androidApp-release.aab
            pixelcount-wearos/wearosApp-release.aab
            pixelcount-*/PixelCount-*-release.jar
